esphome:
  name: test-nasactl-full
  friendly_name: "Test nasactl Full"

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

wifi:
  ssid: "test"
  password: "test1234"

logger:
  logs:
    component: ERROR

external_components:
  - source: github://paolostivanin/nasactl@main
    components: [ nasactl ]
    refresh: 0s


uart:
  tx_pin: GPIO19
  rx_pin: GPIO22
  baud_rate: 9600
  parity: EVEN

nasactl:
  silence_interval: 100
  retry_interval: 500
  min_retries: 1
  send_timeout: 4000

  fsv_read:
    startup_delay: 5s
    batch_size: 10
    batch_delay: 200ms
    interval: 0s

  debug_log_messages: false
  debug_log_undefined: false

  devices:
    # Hydro Unit
    - address: "20.00.00"
      type: hydro

      water_heater_power:
        name: "DHW Enabled"
      water_heater_mode:
        name: "DHW Mode"
      water_temperature:
        name: "DHW Temperature"
      water_target_temperature:
        name: "DHW Target Temperature"

      phe_out_water_out:
        name: "PHE OUT (Water Out)"
      phe_in_water_return:
        name: "PHE IN (Water Return)"
      indoor_eva_in_temperature:
        name: "EVA In Temp"
      indoor_eva_out_temperature:
        name: "EVA Out Temp"
      water_flow:
        name: "Water Flow"

      dhw_valve_direction:
        name: "3-Way Valve Direction"

      water_law_target_flow_temp:
        name: "Water Law Target Flow Temp"
      indoor_power_consumption:
        name: "Indoor Power Consumption"
      generated_power_last_minute:
        name: "Generated Power Last Minute"
      defrost_status:
        name: "Defrost Status"
      water_pump_status:
        name: "Water Pump Status"
      booster_heater_status:
        name: "Booster Heater Status"

      silence_mode:
        name: "Silence Mode"
      water_law_target_temp_shift:
        name: "Water Law Target Temp Shift"

      heating_water_outlet_temp_upper:
        name: "Heating Water Outlet Upper Limit"
      heating_water_outlet_temp_lower:
        name: "Heating Water Outlet Lower Limit"

      heating_lower_outdoor_temp:
        name: "Heating Lower Outdoor Temp"
      heating_upper_outdoor_temp:
        name: "Heating Upper Outdoor Temp"
      heating_water_temp_cold_outdoor:
        name: "Heating Water Temp at Cold Outdoor"
      heating_water_temp_warm_outdoor:
        name: "Heating Water Temp at Warm Outdoor"

      dhw_tank_temp_upper:
        name: "DHW Tank Temp Upper Limit"
      dhw_tank_temp_lower:
        name: "DHW Tank Temp Lower Limit"

      dhw_operation_mode:
        name: "DHW Operation Mode"
      dhw_booster_heater:
        name: "DHW Booster Heater"
      dhw_booster_heater_delay:
        name: "DHW Booster Heater Delay"
      dhw_booster_heater_overshoot:
        name: "DHW Booster Heater Overshoot"

      dhw_forced_operation_timer:
        name: "DHW Forced Operation Timer"
      dhw_forced_operation_time:
        name: "DHW Forced Operation Time"

      dhw_disinfection_enable:
        name: "DHW Disinfection"
      dhw_disinfection_day:
        name: "DHW Disinfection Day"
      dhw_disinfection_start_time:
        name: "DHW Disinfection Start Time"
      dhw_disinfection_target_temp:
        name: "DHW Disinfection Target Temp"
      dhw_disinfection_duration:
        name: "DHW Disinfection Duration"
      dhw_disinfection_max_time:
        name: "DHW Disinfection Max Time"

      hp_max_temp_alone:
        name: "HP Max Temp Alone"
      hp_temp_diff_off:
        name: "HP Temp Diff for OFF"
      hp_temp_diff_on:
        name: "HP Temp Diff for ON"

      heating_dhw_priority:
        name: "Heating DHW Priority"
      heating_priority_changeover_temp:
        name: "Heating Priority Changeover Temp"
      heating_dhw_off_outdoor_temp:
        name: "Heating DHW OFF Outdoor Temp"

      heating_inverter_pump_application:
        name: "Heating Inverter Pump Application"
      heating_inverter_pump_target_delta:
        name: "Heating Inverter Pump Target Delta"

    # AC Units
    - address: "20.00.01"
      type: ac
      climate:
        name: "AC LP Bedroom"
      room_temperature:
        name: "LP Bedroom Temperature"
      indoor_eva_in_temperature:
        name: "LP Bedroom EVA In"
      indoor_eva_out_temperature:
        name: "LP Bedroom EVA Out"

    - address: "20.00.02"
      type: ac
      climate:
        name: "AC Offices"
      room_temperature:
        name: "Offices Temperature"
      indoor_eva_in_temperature:
        name: "Offices EVA In"
      indoor_eva_out_temperature:
        name: "Offices EVA Out"

    - address: "20.00.04"
      type: ac
      climate:
        name: "AC Kids Bedroom"
      room_temperature:
        name: "Kids Bedroom Temperature"
      indoor_eva_in_temperature:
        name: "Kids Bedroom EVA In"
      indoor_eva_out_temperature:
        name: "Kids Bedroom EVA Out"

    - address: "20.00.06"
      type: ac
      climate:
        name: "AC Living Room"
      room_temperature:
        name: "Living Room Temperature"
      indoor_eva_in_temperature:
        name: "Living Room EVA In"
      indoor_eva_out_temperature:
        name: "Living Room EVA Out"

    # Outdoor Unit
    - address: "10.00.00"
      type: outdoor
      error_code:
        name: "Error Code"
      outdoor_operation_odu_mode:
        name: "ODU Mode"
      outdoor_operation_heatcool:
        name: "ODU Heat/Cool"
      outdoor_instantaneous_power:
        name: "Outdoor Instantaneous Power"
      outdoor_cumulative_energy:
        name: "Outdoor Cumulative Energy"
      outdoor_current:
        name: "Outdoor Current"
      outdoor_voltage:
        name: "Outdoor Voltage"
      outdoor_temperature:
        name: "Outdoor Temperature"
      compressor_frequency:
        name: "Compressor Frequency"
      outdoor_fan_speed:
        name: "Outdoor Fan Speed"
