"""
NASA message code definitions for nasactl.

To add a new entity, add an entry to ENTITIES below. Each entry maps a YAML
config key to a NASA message definition. No C++ changes needed.

Supported types: sensor, number, select, switch, binary_sensor, text_sensor

Fields:
  type        (required) Entity type
  code        (required) NASA message hex code
  unit        (optional) Unit of measurement
  device_class(optional) HA device class
  state_class (optional) HA state class (measurement, total_increasing, etc.)
  accuracy    (optional) Decimal places, default 0
  icon        (optional) MDI icon
  divisor     (optional) Read: x/divisor, Write: x*divisor
  multiplier  (optional) Read: x*multiplier, Write: x/multiplier
  signed      (optional) If True, treat raw value as int16. Default False
  fsv         (optional) If True, this is a Field Setting Value (polled on
                         startup, not broadcast)
  min         (optional) Number min value
  max         (optional) Number max value
  step        (optional) Number step
  options     (optional) Select options list
  offset      (optional) Select offset (NASA value = option_index + offset)
  mapping     (optional) Text sensor value-to-string mapping dict
  entity_category (optional) "config" or "diagnostic"
"""

ENTITIES = {
    # =========================================================================
    # SENSORS (read-only numeric)
    # =========================================================================

    # --- Indoor / Hydro sensors ---
    "water_temperature": {
        "type": "sensor",
        "code": 0x4237,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "accuracy": 1,
        "icon": "mdi:thermometer-water",
        "divisor": 10,
        "signed": True,
    },
    "phe_out_water_out": {
        "type": "sensor",
        "code": 0x4238,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "accuracy": 1,
        "icon": "mdi:thermometer",
        "divisor": 10,
        "signed": True,
    },
    "phe_in_water_return": {
        "type": "sensor",
        "code": 0x4236,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "accuracy": 1,
        "icon": "mdi:thermometer",
        "divisor": 10,
        "signed": True,
    },
    "water_flow": {
        "type": "sensor",
        "code": 0x42E9,
        "unit": "L/min",
        "device_class": "volume_flow_rate",
        "state_class": "measurement",
        "accuracy": 1,
        "icon": "mdi:water-pump",
        "divisor": 10,
    },
    "water_law_target_flow_temp": {
        "type": "sensor",
        "code": 0x427F,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "accuracy": 1,
        "icon": "mdi:thermometer-auto",
        "divisor": 10,
        "signed": True,
    },
    "indoor_power_consumption": {
        "type": "sensor",
        "code": 0x4284,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "accuracy": 1,
        "icon": "mdi:flash",
    },
    "indoor_generated_power": {
        "type": "sensor",
        "code": 0x4426,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "accuracy": 1,
        "icon": "mdi:flash",
        "signed": True,
    },
    "indoor_cumulative_energy": {
        "type": "sensor",
        "code": 0x4427,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "accuracy": 3,
        "icon": "mdi:counter",
        "divisor": 1000,
    },
    "room_temperature": {
        "type": "sensor",
        "code": 0x4204,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "accuracy": 1,
        "icon": "mdi:thermometer",
        "divisor": 10,
        "signed": True,
    },
    "indoor_eva_in_temperature": {
        "type": "sensor",
        "code": 0x4205,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "accuracy": 1,
        "icon": "mdi:thermometer",
        "divisor": 10,
        "signed": True,
    },
    "indoor_eva_out_temperature": {
        "type": "sensor",
        "code": 0x4206,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "accuracy": 1,
        "icon": "mdi:thermometer",
        "divisor": 10,
        "signed": True,
    },

    # --- Outdoor unit sensors ---
    "outdoor_temperature": {
        "type": "sensor",
        "code": 0x8204,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "accuracy": 1,
        "icon": "mdi:thermometer",
        "divisor": 10,
        "signed": True,
    },
    "outdoor_instantaneous_power": {
        "type": "sensor",
        "code": 0x8413,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "accuracy": 1,
        "icon": "mdi:flash",
    },
    "outdoor_cumulative_energy": {
        "type": "sensor",
        "code": 0x8414,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "accuracy": 3,
        "icon": "mdi:counter",
        "divisor": 1000,
    },
    "outdoor_current": {
        "type": "sensor",
        "code": 0x8233,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "accuracy": 1,
        "icon": "mdi:current-ac",
        "divisor": 10,
    },
    "outdoor_voltage": {
        "type": "sensor",
        "code": 0x8234,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "accuracy": 0,
        "icon": "mdi:sine-wave",
    },
    "compressor_frequency": {
        "type": "sensor",
        "code": 0x8238,
        "unit": "Hz",
        "device_class": "frequency",
        "state_class": "measurement",
        "accuracy": 0,
        "icon": "mdi:sine-wave",
    },
    "outdoor_fan_speed": {
        "type": "sensor",
        "code": 0x823D,
        "unit": "RPM",
        "state_class": "measurement",
        "accuracy": 0,
        "icon": "mdi:fan",
    },

    # =========================================================================
    # NUMBERS (read-write numeric)
    # =========================================================================

    # --- Temperature targets ---
    "water_target_temperature": {
        "type": "number",
        "code": 0x4235,
        "min": 30, "max": 70, "step": 0.5,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer-water",
        "divisor": 10,
        "signed": True,
    },
    "target_temperature": {
        "type": "number",
        "code": 0x4201,
        "min": 16, "max": 30, "step": 0.5,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer",
        "divisor": 10,
        "signed": True,
    },
    "water_law_target_temp_shift": {
        "type": "number",
        "code": 0x4248,
        "min": -5, "max": 5, "step": 0.5,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer-plus",
        "divisor": 10,
        "signed": True,
    },

    # --- FSV: Heating water outlet limits ---
    "heating_water_outlet_temp_upper": {
        "type": "number",
        "code": 0x424E,
        "min": 37, "max": 55, "step": 1,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer-chevron-up",
        "divisor": 10,
        "signed": True,
        "fsv": True,
        "entity_category": "config",
    },
    "heating_water_outlet_temp_lower": {
        "type": "number",
        "code": 0x424F,
        "min": 15, "max": 37, "step": 1,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer-chevron-down",
        "divisor": 10,
        "signed": True,
        "fsv": True,
        "entity_category": "config",
    },

    # --- FSV: Water law curve ---
    "heating_lower_outdoor_temp": {
        "type": "number",
        "code": 0x4254,
        "min": -20, "max": 5, "step": 1,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:snowflake-thermometer",
        "divisor": 10,
        "signed": True,
        "fsv": True,
        "entity_category": "config",
    },
    "heating_upper_outdoor_temp": {
        "type": "number",
        "code": 0x4255,
        "min": 10, "max": 20, "step": 1,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:sun-thermometer",
        "divisor": 10,
        "signed": True,
        "fsv": True,
        "entity_category": "config",
    },
    "heating_water_temp_cold_outdoor": {
        "type": "number",
        "code": 0x4256,
        "min": 17, "max": 55, "step": 1,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer-high",
        "divisor": 10,
        "signed": True,
        "fsv": True,
        "entity_category": "config",
    },
    "heating_water_temp_warm_outdoor": {
        "type": "number",
        "code": 0x4257,
        "min": 17, "max": 55, "step": 1,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer-low",
        "divisor": 10,
        "signed": True,
        "fsv": True,
        "entity_category": "config",
    },

    # --- FSV: DHW tank limits ---
    "dhw_tank_temp_upper": {
        "type": "number",
        "code": 0x4252,
        "min": 50, "max": 70, "step": 1,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer-chevron-up",
        "divisor": 10,
        "signed": True,
        "fsv": True,
        "entity_category": "config",
    },
    "dhw_tank_temp_lower": {
        "type": "number",
        "code": 0x4253,
        "min": 30, "max": 40, "step": 1,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer-chevron-down",
        "divisor": 10,
        "signed": True,
        "fsv": True,
        "entity_category": "config",
    },

    # --- FSV: DHW disinfection ---
    "dhw_disinfection_start_time": {
        "type": "number",
        "code": 0x4269,
        "min": 0, "max": 23, "step": 1,
        "unit": "h",
        "device_class": "duration",
        "icon": "mdi:clock-start",
        "fsv": True,
        "entity_category": "config",
    },
    "dhw_disinfection_target_temp": {
        "type": "number",
        "code": 0x426A,
        "min": 40, "max": 70, "step": 5,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:virus-off",
        "divisor": 10,
        "signed": True,
        "fsv": True,
        "entity_category": "config",
    },
    "dhw_disinfection_duration": {
        "type": "number",
        "code": 0x426B,
        "min": 5, "max": 60, "step": 5,
        "unit": "min",
        "device_class": "duration",
        "icon": "mdi:timer",
        "fsv": True,
        "entity_category": "config",
    },
    "dhw_disinfection_max_time": {
        "type": "number",
        "code": 0x42CE,
        "min": 1, "max": 24, "step": 1,
        "unit": "h",
        "device_class": "duration",
        "icon": "mdi:timer-alert",
        "divisor": 60,
        "signed": True,
        "fsv": True,
        "entity_category": "config",
    },

    # --- FSV: DHW booster heater ---
    "dhw_booster_heater_delay": {
        "type": "number",
        "code": 0x4266,
        "min": 20, "max": 95, "step": 5,
        "unit": "min",
        "device_class": "duration",
        "icon": "mdi:timer",
        "fsv": True,
        "entity_category": "config",
    },
    "dhw_booster_heater_overshoot": {
        "type": "number",
        "code": 0x4267,
        "min": 0, "max": 4, "step": 1,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer-plus",
        "divisor": 10,
        "signed": True,
        "fsv": True,
        "entity_category": "config",
    },

    # --- FSV: DHW forced operation ---
    "dhw_forced_operation_time": {
        "type": "number",
        "code": 0x426C,
        "min": 30, "max": 300, "step": 10,
        "unit": "min",
        "device_class": "duration",
        "icon": "mdi:timer",
        "multiplier": 10,
        "fsv": True,
        "entity_category": "config",
    },

    # --- FSV: HP tank control ---
    "hp_max_temp_alone": {
        "type": "number",
        "code": 0x4260,
        "min": 45, "max": 53, "step": 1,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:heat-pump",
        "divisor": 10,
        "signed": True,
        "fsv": True,
        "entity_category": "config",
    },
    "hp_temp_diff_off": {
        "type": "number",
        "code": 0x4261,
        "min": 0, "max": 10, "step": 1,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer-minus",
        "divisor": 10,
        "signed": True,
        "fsv": True,
        "entity_category": "config",
    },
    "hp_temp_diff_on": {
        "type": "number",
        "code": 0x4262,
        "min": 5, "max": 30, "step": 1,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer-plus",
        "divisor": 10,
        "signed": True,
        "fsv": True,
        "entity_category": "config",
    },

    # --- FSV: Heating priority ---
    "heating_priority_changeover_temp": {
        "type": "number",
        "code": 0x426D,
        "min": -15, "max": 20, "step": 1,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:swap-horizontal",
        "divisor": 10,
        "signed": True,
        "fsv": True,
        "entity_category": "config",
    },
    "heating_dhw_off_outdoor_temp": {
        "type": "number",
        "code": 0x426E,
        "min": 10, "max": 35, "step": 1,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer-off",
        "divisor": 10,
        "signed": True,
        "fsv": True,
        "entity_category": "config",
    },

    # --- FSV: Inverter pump ---
    "heating_inverter_pump_target_delta": {
        "type": "number",
        "code": 0x428A,
        "min": 2, "max": 8, "step": 1,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:delta",
        "divisor": 10,
        "signed": True,
        "fsv": True,
        "entity_category": "config",
    },

    # =========================================================================
    # SELECTS (read-write enum)
    # =========================================================================

    "water_heater_mode": {
        "type": "select",
        "code": 0x4066,
        "options": ["Economy", "Standard", "Power", "Force"],
        "icon": "mdi:water-boiler",
    },
    "mode": {
        "type": "select",
        "code": 0x4001,
        "options": ["Auto", "Cool", "Dry", "Fan", "Heat"],
        "icon": "mdi:hvac",
    },
    "dhw_operation_mode": {
        "type": "select",
        "code": 0x4097,
        "options": ["Off", "Thermo (On) #1", "Thermo (Off) #2"],
        "icon": "mdi:water-boiler",
        "fsv": True,
        "entity_category": "config",
    },
    "dhw_disinfection_day": {
        "type": "select",
        "code": 0x409A,
        "options": ["Sunday", "Monday", "Tuesday", "Wednesday",
                    "Thursday", "Friday", "Saturday", "All"],
        "icon": "mdi:calendar",
        "fsv": True,
        "entity_category": "config",
    },
    "heating_dhw_priority": {
        "type": "select",
        "code": 0x409E,
        "options": ["DHW", "Heating"],
        "icon": "mdi:priority-high",
        "fsv": True,
        "entity_category": "config",
    },
    "heating_inverter_pump_application": {
        "type": "select",
        "code": 0x40C2,
        "options": ["Not use", "Output 100%", "Output 70%"],
        "icon": "mdi:pump",
        "fsv": True,
        "entity_category": "config",
    },

    # =========================================================================
    # SWITCHES (read-write boolean)
    # =========================================================================

    "water_heater_power": {
        "type": "switch",
        "code": 0x4065,
        "icon": "mdi:water-boiler",
    },
    "power": {
        "type": "switch",
        "code": 0x4000,
        "icon": "mdi:power",
    },
    "silence_mode": {
        "type": "switch",
        "code": 0x4046,
        "icon": "mdi:volume-off",
    },
    "dhw_disinfection_enable": {
        "type": "switch",
        "code": 0x4099,
        "icon": "mdi:virus-off",
        "fsv": True,
        "entity_category": "config",
    },
    "dhw_booster_heater": {
        "type": "switch",
        "code": 0x4098,
        "icon": "mdi:radiator",
        "fsv": True,
        "entity_category": "config",
    },
    "dhw_forced_operation_timer": {
        "type": "switch",
        "code": 0x409B,
        "icon": "mdi:timer-cog",
        "fsv": True,
        "entity_category": "config",
    },

    # =========================================================================
    # BINARY SENSORS (read-only boolean)
    # =========================================================================

    "defrost_status": {
        "type": "binary_sensor",
        "code": 0x402E,
        "icon": "mdi:snowflake-melt",
    },
    "water_pump_status": {
        "type": "binary_sensor",
        "code": 0x4089,
        "icon": "mdi:pump",
    },
    "booster_heater_status": {
        "type": "binary_sensor",
        "code": 0x4087,
        "icon": "mdi:radiator",
        "device_class": "heat",
    },

    # =========================================================================
    # TEXT SENSORS (read-only with value mapping)
    # =========================================================================

    "dhw_valve_direction": {
        "type": "text_sensor",
        "code": 0x4067,
        "icon": "mdi:valve",
        "mapping": {
            0: "Room",
            1: "Tank",
        },
    },
    "error_code": {
        "type": "text_sensor",
        "code": 0x8235,
        "icon": "mdi:alert-circle",
        "entity_category": "diagnostic",
        "mapping": {
            0: "No Error",
            # Communication & System
            101: "Wire Connection Error (Control Kit/ODU)",
            120: "Zone 2 Room Sensor Error (Open/Short)",
            121: "Zone 1 Room Sensor Error (Open/Short)",
            122: "Indoor EVA-IN Sensor Error",
            123: "Indoor EVA-OUT Sensor Error",
            162: "Control Kit EEPROM Error",
            163: "EEPROM Option Setting Error",
            177: "Emergency Signal Error (Hydro Box)",
            198: "Terminal Block Thermal Fuse Open",
            201: "Communication Matching Error",
            202: "Communication Error (ODU Timeout 3m)",
            203: "Comm Error: Inverter to Main Micom",
            205: "Comm Error: Inv Micom to Fan Micom",
            # Outdoor unit sensors
            221: "ODU Ambient Temp Sensor Error",
            231: "Condenser Temp Sensor Error",
            241: "ODU Cond-Out Sensor Breakaway",
            251: "Discharge Temp Sensor Error",
            262: "Discharge Sensor Breakaway",
            266: "Compressor Top Sensor Breakaway",
            269: "Suction Sensor Breakaway",
            276: "Comp Top Temp Sensor Error",
            291: "High Pressure Sensor Error",
            296: "Low Pressure Sensor Error",
            308: "Suction Sensor Error",
            320: "OLP Sensor Error",
            321: "EVI Inlet Sensor Error",
            322: "EVI Outlet Sensor Error",
            381: "Inverter 1 PCB Overheat",
            # Protection & Mechanical
            403: "PHE Freeze Detection (Cooling)",
            404: "Outdoor Unit Overload Protection",
            407: "High Pressure Protection (Comp Down)",
            410: "Low Pressure Protection (Comp Down)",
            416: "Compressor Discharge Overheat",
            425: "Power Line Missing (3-Phase Model)",
            428: "Compression Ratio Control Error",
            436: "PHE Freeze Detection (Heating)",
            438: "EVI EEV Opening Error",
            439: "Refrigerant Leakage (Standby)",
            440: "Heating Blocked (Outdoor >35C)",
            441: "Cooling Blocked (Outdoor <9C)",
            443: "No Startup: Low Pressure",
            450: "High Condenser Temp Error",
            458: "ODU Fan 1 Error",
            # Inverter & Power
            461: "Inverter: Comp Startup Error",
            462: "Inverter: Total/PFC Overcurrent",
            463: "OLP Overheated",
            464: "Inverter: IPM Overcurrent",
            465: "Compressor V Limit Error",
            466: "DC-Link Under/Over Voltage",
            467: "Inverter: Comp Rotation Error",
            468: "Inverter: Current Sensor Error",
            469: "Inverter: DC-Link Voltage Sensor Error",
            470: "ODU EEPROM Read/Write Error",
            471: "ODU EEPROM OTP Error",
            474: "IPM or PFCM Temp Sensor Error",
            475: "ODU Fan 2 Error",
            483: "H/W DC-Link Over Voltage",
            484: "PFC Overload Error",
            485: "Input Current Sensor Error",
            488: "AC Input Voltage Sensor Error",
            500: "IPM Overheat Error",
            507: "High Pressure Switch Trip",
            536: "PHE Refrigerant Leak Error",
            554: "Gas Leak Error",
            590: "Inverter: Data Flash Error",
            # Remote & Controller
            601: "Comm Error: Control Kit to Remote",
            602: "Remote Controller Main/Sub Setting Error",
            604: "Tracking Error: Control Kit to Remote",
            607: "Comm Error: Main to Sub Remote",
            670: "Controller Combination Error",
            # Hydro specific
            897: "DHW Tank Inlet Sensor Error",
            899: "Zone 1 Water-Out Sensor Error",
            900: "Zone 2 Water-Out Sensor Error",
            901: "Inlet Water (PHE) Sensor Error",
            902: "Outlet Water (PHE) Sensor Error",
            903: "Backup Heater Outlet Sensor Error",
            904: "DHW Tank Sensor Error",
            906: "ODU Evap-In Sensor Error",
            907: "Pipe Rupture Protection Error",
            908: "Freeze Prevention (Auto-Restart)",
            909: "Freeze Prevention (Manual Reset)",
            910: "Water Outlet Pipe Sensor Detached",
            911: "Low Water Flow Rate Error",
            913: "Flow Switch Error (6x Detection)",
            914: "Incorrect Thermostat Connection",
            915: "DC Fan Error (Non-operating)",
            916: "Mixing Valve Sensor Error",
            919: "DHW Disinfection Temp Not Reached",
            920: "FSV SD Card Read Error",
            973: "Water Pressure Sensor Error",
        },
    },
    "outdoor_service_operation": {
        "type": "text_sensor",
        "code": 0x8000,
        "icon": "mdi:engine",
        "mapping": {
            0: "Not Active",
            2: "Heating Test Run",
            3: "Pump Out",
            13: "Cooling Test Run",
            14: "Pump Down",
        },
    },
    "outdoor_driving_mode": {
        "type": "text_sensor",
        "code": 0x8001,
        "icon": "mdi:engine",
        "mapping": {
            0: "Stop",
            1: "Safety",
            2: "Normal",
            3: "Balance",
            4: "Recovery",
            5: "Deice",
            6: "Comp Down",
            7: "Prohibit",
            8: "Line Jig",
            9: "PCB Jig",
            10: "Test Mode",
            11: "Recharge",
            12: "Pump Down",
            13: "Pump Out",
            14: "Vacuum",
            15: "Calory Jig",
            16: "Pump Down Stop",
            17: "Sub Stop",
            18: "Check Pipe",
            19: "Check Ref",
            20: "FPT Jig",
            21: "Nonstop Heat/Cool Change",
            22: "Auto Inspect",
            23: "Electric Discharge",
            24: "Split Deice",
            25: "Inverter Check",
            26: "Nonstop Deice",
            27: "Remote Test",
            28: "Rating",
            29: "PC Test",
            30: "Pump Down Thermo-off",
            31: "3-Phase Test",
            32: "Smart Install",
            33: "Deice Perf Test",
            34: "Inverter Fan PBA Check",
            35: "Auto Pipe Pairing",
            36: "Auto Charge",
        },
    },
}
